#!/usr/bin/env node
// Rebuilds the browser bundle (esbuild, same options as `npm run build:web`)
// and splices it into tool/index.html between the BUNDLE:START / BUNDLE:END
// markers. This is the only supported way to update the bundle — never edit
// the spliced <script> by hand.
'use strict';

const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'tool', 'index.html');
const outfile = path.join(root, 'dist', 'bundle.js');

const START = '<!-- BUNDLE:START — generated by scripts/build-tool.js; never edit by hand -->';
const END = '<!-- BUNDLE:END -->';

function fail(msg) {
  console.error('build-tool: ' + msg);
  process.exit(1);
}

function countOccurrences(haystack, needle) {
  let count = 0;
  let i = haystack.indexOf(needle);
  while (i !== -1) {
    count += 1;
    i = haystack.indexOf(needle, i + needle.length);
  }
  return count;
}

require('esbuild').buildSync({
  entryPoints: [path.join(root, 'src', 'browser-entry.js')],
  bundle: true,
  platform: 'browser',
  format: 'iife',
  minify: true,
  outfile,
});

const bundle = fs.readFileSync(outfile, 'utf8');
const html = fs.readFileSync(htmlPath, 'utf8');

if (countOccurrences(html, START) !== 1) fail('expected exactly one BUNDLE:START marker in tool/index.html');
if (countOccurrences(html, END) !== 1) fail('expected exactly one BUNDLE:END marker in tool/index.html');

const afterStart = html.indexOf(START) + START.length;
const endIdx = html.indexOf(END);
if (endIdx < afterStart) fail('BUNDLE:END marker appears before BUNDLE:START');

const spliced = html.slice(0, afterStart) + '\n<script>\n' + bundle + '</script>\n' + html.slice(endIdx);
fs.writeFileSync(htmlPath, spliced);
console.log('build-tool: spliced ' + Buffer.byteLength(bundle) + ' bytes of bundle into tool/index.html');
